{
  description = "Matt's multi-platform nix configuration";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
    matt-nixpkgs.url = "github:mattrobenolt/nixpkgs";
    nix-darwin.url = "github:nix-darwin/nix-darwin/master";
    nix-darwin.inputs.nixpkgs.follows = "nixpkgs";
    home-manager.url = "github:nix-community/home-manager";
    home-manager.inputs.nixpkgs.follows = "nixpkgs";
  };

  outputs =
    {
      self,
      matt-nixpkgs,
      nix-darwin,
      home-manager,
      ...
    }:
    {
      # ============================================================================
      # macOS Systems (nix-darwin)
      # ============================================================================

      darwinConfigurations = {
        # Work MacBook Pro
        "Matts-MacBook-Pro" = nix-darwin.lib.darwinSystem {
          specialArgs = { inherit matt-nixpkgs; };
          modules = [
            # Shared config (common packages, settings)
            ./common.nix

            # Host-specific config
            ./hosts/darwin/work.nix

            # Set git commit hash for darwin-version
            {
              system.configurationRevision = self.rev or self.dirtyRev or null;
            }

            # home-manager integration
            home-manager.darwinModules.home-manager
            {
              home-manager = {
                useGlobalPkgs = true;
                useUserPackages = true;
                backupFileExtension = "backup";
                users.matt = import ./home.nix;
                # Disable home-manager's nix management when system nix is disabled
                sharedModules = [
                  { nix.enable = false; }
                ];
              };
            }
          ];
        };

        # Add more Darwin hosts here as needed:
        # "Matts-Personal" = nix-darwin.lib.darwinSystem {
        #   modules = [
        #     ./common.nix
        #     ./hosts/darwin/personal.nix
        #     home-manager.darwinModules.home-manager
        #     { home-manager.users.matt = import ./home.nix; }
        #   ];
        # };
      };

      # ============================================================================
      # NixOS Systems
      # ============================================================================

      nixosConfigurations = {
        # Example NixOS machine (template)
        # "nixos-example" = nixpkgs.lib.nixosSystem {
        #   system = "x86_64-linux";  # or "aarch64-linux" for ARM
        #   modules = [
        #     # Shared config (common packages)
        #     ./common.nix
        #
        #     # Host-specific config
        #     ./hosts/nixos/example.nix
        #
        #     # Hardware config (generated by nixos-generate-config)
        #     # ./hosts/nixos/example-hardware.nix
        #
        #     # home-manager integration
        #     home-manager.nixosModules.home-manager
        #     {
        #       home-manager.useGlobalPkgs = true;
        #       home-manager.useUserPackages = true;
        #       home-manager.users.matt = import ./home.nix;
        #     }
        #   ];
        # };

        # Add your actual NixOS hosts here
      };
    };
}
